#!/bin/bash

mv $HOME/.zshrc $HOME/.zshrc_bak

sh -c "RUNZSH=no $(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --skip-chsh"

opam init --auto-setup --disable-sandboxing

